[project]
name = "hightlight-bouldering"
version = "0.1.0"
description = "Automatic bouldering highlight video recognition project"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.2.0",
    "pytubefix>=10.3.6",
    "pytuber>=22.5",
]
